Feature/421 keybinding refactoring
ElektraInitiative/PermaplanT pull request #1016
Opened 2023-10-26 23:00 UTC by danielsteinkogler

## Basics

- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

2023-11-01 06:15 UTC, markus2330 requested changes
Great job, looks good to me. Only a few fixes to be consistent with terms in the concept.

2023-11-01 06:15 UTC, markus2330 commented on frontend/src/config/keybindings/index.ts
> +  keyHandlerActions: Record<string, () => void>,
Also rename here to keyBindingsActions

2023-11-01 06:15 UTC, markus2330 commented on frontend/src/config/keybindings/index.ts
> + * @param keyHandlerActions - An object that maps action names to corresponding handler functions.
Also rename here. Write that it is an array.

2023-11-01 06:15 UTC, markus2330 commented on frontend/src/config/keybindings/index.ts
> +export const KEYBINDING_SCOPE_PLANTS_LAYER = 'plants_layer';
add all the layers

2023-11-01 06:15 UTC, markus2330 commented on frontend/src/config/keybindings/index.ts
> +type KeyBindingConfig = {
consistently plural?

```suggestion
type KeyBindingsConfig = {
```

2023-11-08 20:50 UTC, danielsteinkogler commented
@markus2330 i think we can merge this after approval

2023-11-09 06:57 UTC, markus2330 requested changes
Needs rebase. Could you please add keyhandler and keybinding to glossary.

2023-11-09 16:28 UTC, danielsteinkogler commented
@markus2330 i rebased and added the terms to glossary. Please check if the description is okay for you.

2023-11-10 05:22 UTC, markus2330 approved these changes
Great, much clearer.

2023-11-10 05:22 UTC, merged