Added install guide for nvm and rust to dev setup
ElektraInitiative/PermaplanT pull request #103
Opened 2023-03-13 17:06 UTC by NurramoX

## Basics

- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

2023-03-15 08:22 UTC, badnames requested changes
Great guide, well done. 

Please provide a link to this document in the respective README files in frontend and backend, so that new developers can easily find this information.

2023-03-15 12:48 UTC, aidnurs approved these changes

2023-03-15 13:42 UTC, markus2330 approved these changes
Great job! Only some minor details. I did not try the tutorial, though.

2023-03-15 13:42 UTC, markus2330 commented on doc/development_setup.md
> +### Installing rust + cargo
There are several capitalization problems, please make sure names and titles are capitalized, e.g.:

```suggestion
### Installing Rust + Cargo
```

2023-03-15 13:42 UTC, markus2330 commented on doc/development_setup.md
> +$ curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
This maybe does now the right thing, but it won't if Rust gets upgraded in future. In backend README we defined we want to use Rust 1.67.1, so please install this version.

2023-03-15 13:42 UTC, markus2330 commented on doc/development_setup.md
> +On Windows, go to https://www.rust-lang.org/tools/install and follow the instructions for installing Rust. At some point in the installation, you’ll receive a message explaining that you’ll also need
Please read documentation guidelines (doc/documentation.md), we use line breaks for every sentence:
```suggestion
On Windows, go to https://www.rust-lang.org/tools/install and follow the instructions for installing Rust.
At some point in the installation, you’ll receive a message explaining that you’ll also need the MSVC build tools for Visual Studio 2013 or later.
```

2023-03-15 13:43 UTC, markus2330 commented
> Please provide a link to this document in the respective README files in frontend and backend, so that new developers can easily find this information.

I agree, good catch! Can you please also check for my requested changes when you review again? (@NurramoX request his review when you did the requested changes.)

2023-03-15 14:02 UTC, badnames commented
> Can you please also check for my requested changes when you review again?

Yes of course.

2023-03-28 10:55 UTC, badnames approved these changes

2023-03-28 11:47 UTC, merged

2023-03-28 11:47 UTC, markus2330 commented
Great job!