84 landing page prototype
ElektraInitiative/PermaplanT pull request #107
Opened 2023-03-14 19:20 UTC by absurd-turtle

## Basics

- [x ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ x] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I fixed all affected decisions
- [x] I added code comments, logging, and assertions as appropriate
- [x] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

2023-03-16 19:04 UTC, markus2330 commented
@yvonnemarkl really likes your logos!!! :rocket:

2023-03-22 14:01 UTC, markus2330 requested changes
PermaplanT is sometimes wrongly capitalized, more info comes in an issue.

2023-03-22 14:01 UTC, markus2330 commented on frontend/src/features/landing_page/routes/LandingPage.tsx
> +          href="https://github.com/ElektraInitiative/PermaPlant/"
```suggestion
          href="https://github.com/ElektraInitiative/Permaplant/"
```

2023-03-22 14:01 UTC, markus2330 commented on frontend/src/routes/index.ts
> +    title: 'PermaPlanT',
```suggestion
    title: 'PermaplanT',
```

2023-03-27 07:05 UTC, markus2330 commented
Please tell us when we can take a look. We are already very curios! :heart:

2023-03-27 10:17 UTC, absurd-turtle commented
> Please tell us when we can take a look. We are already very curios! heart

You can have a look at it again. I have implemented a dark mode(almost complete), did some structural changes to the UI (colors, button component) and tried to include your suggestions.

2023-03-28 16:29 UTC, markus2330 commented
@buenaflor would be great if you can make a short review, then you maybe need to fix less later :wink:

2023-03-29 10:07 UTC, markus2330 requested changes
Please rebase and add documentation for the components you changed.

2023-03-29 12:10 UTC, absurd-turtle commented
> Please rebase and add documentation for the components you changed.

done

2023-03-29 12:11 UTC, absurd-turtle commented
> Please rebase and add documentation for the components you changed.

done

2023-03-29 12:43 UTC, markus2330 approved these changes

2023-03-29 12:43 UTC, merged