Feature/1138 area of plants amount indicator
ElektraInitiative/PermaplanT pull request #1141
Opened 2023-12-22 12:38 UTC by Bushuo

> [!CAUTION]
> Merge #1118 first, this branch is based on it.

## Basics

- [X] I added a line to [changelog.md](/doc/changelog.md)
- [X] The PR is rebased with current master.
- [X] Details of what you changed are in commit messages.
- [X] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

2023-12-22 15:55 UTC, markus2330 commented
CI fails, would be great if it builds (maybe just a formatting problem), so that we can have a look on it.

2023-12-22 16:20 UTC, Bushuo commented
Somehow those are files that I never touched 😂

2024-01-03 09:12 UTC, markus2330 requested changes
Great job!

- [ ] Plants -> plants in the amount indicator
- [ ] the multiplication result of the plants would be useful, e.g. it should read ` 7 x 2 = 14 plants`
- [x] if you move the cursor to the very right, you don't see the plants amount indicator. I think it is difficult to fix and we don't think it is a problem though. (just a note)
- [x] the tour looks very differently, is this on purpose? (just a question)

2024-01-03 09:12 UTC, markus2330 commented on frontend/src/config/env.ts
> +// queries and mutations will be executed even if no internet connection is available
Please write about such changes also in changelog.md

2024-01-03 11:20 UTC, Bushuo commented
@markus2330 

I checked in your change request.

> the tour looks very differently, is this on purpose?
Does the tour on master look different? Maybe it has to do with the changes I made to the tailwind config. If so I will take a look at it.

2024-01-03 14:51 UTC, Bushuo commented
@markus2330 
I changed the prettier config for import sorting a little bit, I hope this is not a problem.
Eventual merge conflicts should be relatively easy to fix. Basically accept one of them and use auto import to sort it out.

The last commit therefore adds a bunch of changed files.

2024-01-03 17:23 UTC, markus2330 commented
> Does the tour on master look different?

It looked quite different on your PR when I tried it before but now I checked it again and Yvonne and me liked it very much. So it does not really matter if it changed or not. If it changed, it is now better. So everything a-okay :+1: 

Btw. in theory you can check on dev.permaplant.net how master looks like. For the tour it is a problem though if you already clicked it away... :wink: 

> I changed the prettier config for import sorting a little bit, I hope this is not a problem.

It is not a problem and actually I think this specific reformatting is a good idea. It would be better though if reformatting is done in separate PRs, as this makes reviewing much easier. (Reformatting PRs don't really need a review, except of the changed setting and changelog.md).

I hope @danielsteinkogler can nevertheless review it. Actually, it should be possible to filter out individual commits in a review.

2024-01-04 20:25 UTC, Bushuo commented
@danielsteinkogler Yup, viewing only a range of commits in the review panel works.
Don't select the last 3 commits. 
I'm sorry 😅

2024-01-07 17:58 UTC, danielsteinkogler commented
jenkins build please

2024-01-07 19:36 UTC, Bushuo commented
I cherry picked the test fixes now into this branch to get this merged asap

2024-01-07 19:59 UTC, Bushuo commented
jenkins build please

2024-01-08 05:07 UTC, markus2330 approved these changes
Great job! :heart:

2024-01-08 05:07 UTC, markus2330 commented on doc/changelog.md
> +- Add a dev env variable for react query when developing in offline env (e.g. plane) _(Paul)_
What is the name of this env var?
In general: Try to keep env vars as minimal as possible, only add them when you really need to change it from time to time.

2024-01-08 05:08 UTC, merged