Feature/977 add note field to plant details
ElektraInitiative/PermaplanT pull request #1188
Opened 2024-02-16 16:47 UTC by danielsteinkogler

## Basics

- [ ] The PR is rebased with current master
- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] Details of what I changed are in the commit messages
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog
- [ ] The buildserver is happy

## Checklist

- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## First Time Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I am using [Tailwind CSS Linting](https://tailwindcss.com/blog/introducing-linting-for-tailwindcss-intellisense)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines
- [ ] I've checked conformity to requirements
- [ ] I've checked that the requirements are tested

2024-02-16 17:40 UTC, danielsteinkogler commented
jenkins build please

2024-02-17 13:39 UTC, danielsteinkogler commented
jenkins build please

2024-02-17 13:54 UTC, danielsteinkogler commented
jenkins build please

2024-02-19 05:37 UTC, markus2330 commented
jenkins build please

2024-02-25 14:25 UTC, Bushuo requested changes
Sorry reviewing took so long. Please check my remarks.

2024-02-25 14:25 UTC, Bushuo commented on frontend/src/components/Form/MarkdownEditor.tsx
> +    execute: function execute(state, api, dispatch, executeCommandState, shortcuts) {
```suggestion
    execute(state, api, dispatch, executeCommandState, shortcuts) {
```
Would make it more readable IMO

2024-02-25 14:25 UTC, Bushuo commented on frontend/src/features/map_planning/store/UntrackedMapStore.ts
> +  setPlantingDetailNotesFullscreen(isFullscreen: boolean) {
Is this unused?

2024-02-26 15:58 UTC, Bushuo approved these changes

2024-02-26 17:12 UTC, merged

2024-02-26 17:13 UTC, markus2330 commented
Fantastic work, thank you! :heart: