Feature/1130 timeline event representation
ElektraInitiative/PermaplanT pull request #1192
Opened 2024-02-20 17:00 UTC by danielsteinkogler

## Basics

- [ ] The PR is rebased with current master
- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] Details of what I changed are in the commit messages
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog
- [ ] The buildserver is happy

## Checklist

- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## First Time Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I am using [Tailwind CSS Linting](https://tailwindcss.com/blog/introducing-linting-for-tailwindcss-intellisense)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines
- [ ] I've checked conformity to requirements
- [ ] I've checked that the requirements are tested

2024-03-04 12:07 UTC, danielsteinkogler commented
jenkins build please

2024-03-04 13:47 UTC, danielsteinkogler commented
jenkins build please

2024-03-04 13:55 UTC, danielsteinkogler commented
jenkins build please

2024-03-04 15:14 UTC, danielsteinkogler commented
jenkins build please

2024-03-04 15:55 UTC, danielsteinkogler commented
jenkins build please

2024-03-05 10:15 UTC, danielsteinkogler commented
jenkins build please

2024-03-05 11:35 UTC, danielsteinkogler commented
jenkins build please

2024-03-08 09:43 UTC, danielsteinkogler commented
jenkins build please

2024-03-08 09:48 UTC, danielsteinkogler commented
jenkins build please

2024-03-08 10:11 UTC, danielsteinkogler commented on e2e/features/timeline.feature
> +    # TODO Fix Test (#1202)
i created a left over issue to fix this scenario. i currently don't know why it is failing. When i test it manually it seems to work.

2024-03-10 17:50 UTC, markus2330 commented
jenkins build please

2024-03-10 17:58 UTC, markus2330 commented
jenkins build please

2024-03-10 18:10 UTC, markus2330 commented
jenkins build please

2024-03-10 18:33 UTC, markus2330 commented
jenkins build please

2024-03-11 07:46 UTC, markus2330 requested changes
Thx for the PR! Finally it built!

We did not see any visual representation of events in the timeline. Please add a (manual) test how to get events into the timeline.

2024-03-11 08:41 UTC, danielsteinkogler commented
jenkins build please

2024-03-11 18:22 UTC, markus2330 commented
jenkins build please

2024-03-11 19:08 UTC, markus2330 approved these changes
**Excellent** work, we are very happy :heart:

2024-03-13 06:19 UTC, danielsteinkogler commented
jenkins build please

2024-03-13 08:38 UTC, merged