feat(#1136); add missing toast messages
ElektraInitiative/PermaplanT pull request #1194
Opened 2024-02-27 13:06 UTC by danielsteinkogler

## Basics

- [ ] The PR is rebased with current master
- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] Details of what I changed are in the commit messages
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog
- [ ] The buildserver is happy

## Checklist

- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## First Time Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I am using [Tailwind CSS Linting](https://tailwindcss.com/blog/introducing-linting-for-tailwindcss-intellisense)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines
- [ ] I've checked conformity to requirements
- [ ] I've checked that the requirements are tested

2024-02-27 13:09 UTC, danielsteinkogler commented
@Bushuo 
part of the issue is also to remove "autoClose". DId you mean that "autoClose: false" should be removed so that toasts are closed automatically or do you mean that they shouldn't close automatically

2024-02-27 23:04 UTC, danielsteinkogler commented
jenkins build please

2024-02-28 16:30 UTC, Bushuo commented
@danielsteinkogler 
I think I meant to evaluate all query APIs again to see if they really should be closing automatically or not.
I can not really remember anymore what exactly I meant with this comment.
Sorry 😓

2024-02-29 17:39 UTC, markus2330 requested changes
Great job, only a few minor text changes. If it is actual "map data" and not "maps", please keep your text.

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/de/guidedTour.json
> +    "update_tour_status_error": "Sorry, ich habe Schwierigkeiten den Status deiner Einführung in den Map Editor zu aktualisieren.",
Could you actually trigger this error? Is reloading of the page maybe useful?

```suggestion
    "update_tour_status_error": "Entschuldigung, ich habe Schwierigkeiten den Status deiner Einführung zu aktualisieren.",
```

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/de/guidedTour.json
>      "fetch_status_error": "Sorry, ich habe Schwierigkeiten den Status deiner Einführung in den Map Editor zu empfangen. Bitte lade die Seite neu, damit ich es noch einmal versuchen kann.",
```suggestion
    "fetch_status_error": "Entschuldigung, ich habe Schwierigkeiten den Status deiner Einführung in den Map Editor zu empfangen. Bitte lade die Seite neu, damit ich es noch einmal versuchen kann.",
```

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/de/guidedTour.json
> +    "complete_tour_error": "Sorry, ich habe Schwierigkeiten die Einführungstour abzuschließen.",
```suggestion
    "complete_tour_error": "Entschuldigung, ich habe Schwierigkeiten die Einführungstour abzuschließen.",
```

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/de/maps.json
> +    "error_fetch_map_data": "Sorry, ich habe Schwierigkeiten die Karten-Daten von meinem Server zu erhalten. Bitte versuche es später erneut.",
```suggestion
    "error_fetch_map_data": "Entschuldigung, ich habe Schwierigkeiten die Karten von meinem Server zu erhalten. Bitte versuche es später erneut.",
```

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/de/plantRelations.json
> +  "error_fetching_relations": "Sorry, ich habe Schwierigkeiten die Beziehungen zwischen den Plfanzen zu laden. Bitte versuche es später noch einmal."
```suggestion
  "error_fetching_relations": "Entschuldigung, ich habe Schwierigkeiten die Beziehungen zwischen den Pflanzen zu laden. Bitte versuche es später noch einmal."
```

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/en/guidedTour.json
> +    "update_tour_status_error": "Sorry, I'm experiencing trouble updating the status of your introduction to the Map Editor.",
```suggestion
    "update_tour_status_error": "Sorry, I'm experiencing trouble updating the status of your introduction tour.",
```

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/en/guidedTour.json
> +    "complete_tour_error": "Sorry, I'm experiencing trouble completing the introduction to the Map Editor.",
```suggestion
    "complete_tour_error": "Sorry, I'm experiencing trouble completing the introduction tour.",
```

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/en/maps.json
> +  "error_fetch_map_data": "Sorry, I'm experiencing trouble fetching map data from my server. Please try again later.",
```suggestion
  "error_fetch_map_data": "Sorry, I'm experiencing trouble fetching maps from my server. Please try again later.",
```

2024-02-29 17:39 UTC, markus2330 commented on frontend/src/config/i18n/en/plantRelations.json
> +  "error_fetching_relations": "Sorry, I'm experiencing trouble fetching plant relations from the server. Please try again later."
```suggestion
  "error_fetching_relations": "Sorry, I'm experiencing trouble fetching plant relations from my server. Please try again later."
```

2024-02-29 17:42 UTC, markus2330 commented
> part of the issue is also to remove "autoClose".

Yes, the default shouldn't be changed so that all toasts close automatically.

2024-03-05 11:11 UTC, danielsteinkogler commented
jenkins build plesae

2024-03-05 11:15 UTC, danielsteinkogler commented
jenkins build please

2024-03-05 11:22 UTC, danielsteinkogler commented
jenkins build please

2024-03-09 13:27 UTC, merged

2024-03-09 13:27 UTC, markus2330 commented
great job, thank you :heart: