feat(#1198): add tooltips for keybindungs
ElektraInitiative/PermaplanT pull request #1199
Opened 2024-03-05 17:32 UTC by danielsteinkogler

## Basics

- [ ] The PR is rebased with current master
- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] Details of what I changed are in the commit messages
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog
- [ ] The buildserver is happy

## Checklist

- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## First Time Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I am using [Tailwind CSS Linting](https://tailwindcss.com/blog/introducing-linting-for-tailwindcss-intellisense)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines
- [ ] I've checked conformity to requirements
- [ ] I've checked that the requirements are tested

2024-03-06 10:34 UTC, danielsteinkogler commented
jenkins build please

2024-03-06 15:39 UTC, Bushuo requested changes
Looks good, but please clarify the points for me 👍

2024-03-06 15:39 UTC, Bushuo commented on frontend/src/config/keybindings/index.ts
> +export function getTooltipStringWithShortcut(
I would prefer a consistent nomenclature. The module is called `keybindings` and in the issue we talk about keybindings as well. Are "shortcuts" not the same as "keybindings".

Additionally, I think that keybinding is not the right word here.
We pass in an action and we get a text description of the keybinding.

So imo the function should be called `getDescriptionForKeybinding` or something.
Also imo the name of a function should not talk about the type it returns.
The functions return type has this purpose.

2024-03-06 15:39 UTC, Bushuo commented on frontend/src/config/keybindings/index.ts
> +  return `${descriptionText || ''} (${getConfiguredShortcutsForAction(scope, action).join(',')})`;
I have not tried if the ` ` space is visible if `descriptionText` is not passed. If so, please remove the space.
```suggestion
  return `${descriptionText || ''} (${getConfiguredShortcutsForAction(scope, action).join(',')})`.trim();
```

2024-03-08 11:05 UTC, danielsteinkogler commented
jenkins build please

2024-03-09 13:44 UTC, markus2330 commented
jenkins build please

2024-03-09 15:07 UTC, markus2330 approved these changes
Thank you, great job! :heart: 

Can you write "Esc" in the tooltip instead of "Escape" (which is what is usually on the keyboards).

I created an left-over issue #1203.

2024-03-11 17:04 UTC, danielsteinkogler commented
@markus2330 i added translation for the keybindings

2024-03-11 18:26 UTC, markus2330 approved these changes
Great job!

2024-03-13 08:23 UTC, merged