mdbook initial setup
ElektraInitiative/PermaplanT pull request #180
Opened 2023-03-29 16:07 UTC by kitzbergerg

# Introduction

Add mdbook: `cargo install mdbook`.  
You can now run `mdbook serve --open` to generate documentation from markdown files in the doc folder.

## Basics

- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

2023-03-30 12:16 UTC, markus2330 approved these changes
Thank you for the PR! Please write in the documentation how the mdbook can be built.

2023-03-30 12:16 UTC, markus2330 commented on doc/SUMMARY.md
> +- [authors](./authors.md)
Can be much later/last.

2023-03-30 12:16 UTC, markus2330 commented on doc/SUMMARY.md
> +- [decisions](./decisions/README.md)
Do we really have to list each one of them? Can we somehow include the whole folder?

2023-03-30 12:16 UTC, markus2330 commented on doc/SUMMARY.md
> +  - [2022_12_16](./meetings/2022_12_16.md)
Same question: Can we somehow include the whole folder?

2023-03-30 12:16 UTC, markus2330 commented on doc/SUMMARY.md
> +
Probably main README.md should be first

2023-03-30 12:16 UTC, markus2330 commented on book.toml
> +authors = ["kitzbergerg"]
Can you link to doc/authors.md here? Otherwise write something generic like "PermaplanT Contributors"

2023-03-30 12:38 UTC, markus2330 commented
I think we also want (from https://github.com/rust-lang/mdBook/wiki/Third-party-plugins)

- maybe toc or [pagetoc](https://github.com/JorelAli/mdBook-pagetoc) for meetings+use cases to not make the left side bar too long
- mermaid
- [linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck)

2023-03-30 15:35 UTC, kitzbergerg commented
Resolved all the threads above as they will be resolved by automatic generating.
 
> Maybe someone already wrote the possibility to include a whole folder? If not, can you open an issue at their tracker, maybe they want such a feature anyway.
 I found [this](https://github.com/cococolanosugar/mdbook-auto-gen-summary). A Rust pre-processor doing exactly that. I can test it and if we need more functionality I would suggest forking it or creating our own.
Writing our own might take a few hours so probably a individual task for 1 week.

2023-04-06 20:18 UTC, kitzbergerg commented
@markus2330 It is now possible to use the preprocessor. To do that run:
```
cargo install --version 0.1.0 --git https://github.com/kitzbergerg/mdbook-generate-summary mdbook-generate-summary
mdbook serve --open
```

The cargo command installs the preprocessor as a binary (I put it in a separate repo as it doesn't really fit here). 
mdbook should now automatically generate all the chapters so from now on we just need to put them in the correct order.

2023-04-08 11:21 UTC, markus2330 requested changes
Great, works for me! Can't wait to get this, very nice way to read documentation.

Please add **within the repository** what exactly needs to be done and please don't write it in the PR description as it may lead to confusion in which directory something actually should be executed. Also `cargo install mdbook` is missing.

2023-04-08 11:21 UTC, markus2330 commented on doc/architecture/README.md
> +# architecture
Should all be capitalized. Please also write a bit about it, e.g. that we use arc42, have a frontend+backend etc.

`1.5. ## Solution` there is some problem, please check the titles.

```suggestion
# Architecture
```

2023-04-08 11:21 UTC, markus2330 commented on doc/meetings/README.md
> +# meetings
```suggestion
# Meetings
```

2023-04-11 06:55 UTC, markus2330 commented
removed this from project and added issue instead

2023-04-11 11:43 UTC, kitzbergerg commented
@markus2330 I released a new version of the preprocessor. To build and view the doc run:
```
cargo install mdbook
cargo install --version 0.1.1 --git https://github.com/kitzbergerg/mdbook-generate-summary mdbook-generate-summary
mdbook serve --open
```

I still have to document the other repo, but apart from that this PR is pretty much done. I would leave the rest to @lukashartl (I'll create a new issue describing what to do).

The question now is pretty much how we want to continue with this. We could either merge it like this and gradually add explanations and references (e.g. were to find backend doc, how to build with mdbook) or make it part of this PR as well. 

One 'breaking change' is that as soon as this PR is merged every directory in doc is required to include a `README.md`. There is the option to disable that in the preprocessor, but I think we should enforce a short explanation as to which directory does what.

2023-04-11 16:59 UTC, markus2330 requested changes
There is still no documentation **within the repository** how to run the mdbook. Please add it to the top-level README.md

2023-04-11 17:06 UTC, markus2330 commented
Yes, I agree, all folders should have a README.md

2023-04-13 16:46 UTC, markus2330 commented on README.md
> +cargo install --version 0.1.1 --git https://github.com/kitzbergerg/mdbook-generate-summary mdbook-generate-summary
For me this compiled and installed mdbook v0.4.28 again?

2023-04-13 16:47 UTC, merged