Meeting notes: 30.03.2023 Polyculture
ElektraInitiative/PermaplanT pull request #186
Opened 2023-03-30 11:03 UTC by Benjaminimal

Here are the notes from today's polyculture meeting.

@markus2330
I created a sheet to gather relationships consistently.
It's linked in the meeting notes.
Please have a look at it.
If you think we can work with this I'll forward it to the other people.

I tried to minimize work when importing this and make adding or changing data as easy as possible.
To reduce duplication, spelling, casing, and whitespace errors I made a "Plants" sheet with full taxonomic information.
When adding relations all you have to do is select values from drop downs.
The currently entered data are just examples and of course not any real relationships.

## Basics

- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

2023-03-30 14:13 UTC, yvonnemarkl commented on doc/meetings/2023_03_30_polyculture.md
> +   Frist the quality of the following datasources is be assessed.
```suggestion
   First the quality of the following datasources has to be assessed.
```

2023-04-02 07:06 UTC, markus2330 requested changes
Thank you for writing the meeting notes, great job to summarize so much content!

2023-04-02 08:29 UTC, Benjaminimal commented on doc/meetings/2023_03_30_polyculture.md
> +   You can find the document [here](https://docs.google.com/spreadsheets/d/1jtsng8H4SkwK2gxK_qF1XkC0ygpjXZgMUKKj1x3TA9M/).
Added a license.

Yes, the examples are not correct.
> The currently entered data are just examples and of course not any real relationships.

2023-04-02 08:31 UTC, Benjaminimal commented on doc/meetings/2023_03_30_polyculture.md
> +     - Family
Those are the names of the ranks the plant belongs to.
"Taxonomic rank" describes on which level the relationship applies.

2023-04-02 08:31 UTC, Benjaminimal commented on doc/meetings/2023_03_30_polyculture.md
> +   - Sources
She can also add columns if she needs to.

2023-04-02 08:42 UTC, Benjaminimal commented on doc/meetings/2023_03_30_polyculture.md
> +   - Left side
See https://github.com/ElektraInitiative/PermaplanT/pull/186/commits/5eecf4782900f6a945cead393351a26da120ab8f

2023-04-06 16:16 UTC, merged