feat: drawing layer
ElektraInitiative/PermaplanT pull request #215
Opened 2023-04-03 22:57 UTC by buenaflor

Adds a drawing layer.

Features:
 - Zooming
 - Dragging
 - Scrolling
 - Single select & multi select of shapes
 - Resizing & rotation of shapes

It's still WIP but if possible test out current features.

There are a couple minor things that need fixing that influence UX.

This was honestly quite difficult so it might take a bit of time to make this experience more smooth.

I also kept support for touchpads in mind so if possible try it out with that as well.

## Basics

- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

2023-04-06 08:43 UTC, markus2330 requested changes
Amazing job, we love this first version from UI perspective!

Important stuff first, to get it merged:

- [ ] write a README.md how to add new layers (docu for other devs)
- [ ] how to reuse common parts (e.g. selection will be used everywhere)
- [ ] write a README explaining how to use the UI (more or less what is written here in the PR description)
- [ ] add more code documentation

From UI perspective (can also be fixed in a later PR, please create an issue if you decide to do so):

- [ ] group selection: selection disappears after objects were moved
- [ ] ctrl should allow multi-selection of different objects (also expanding on group selection)

2023-04-06 08:43 UTC, markus2330 commented on frontend/src/routes/index.ts
> +    path: '/drawing-page',
And please also add a link from landing page (rebase first):

```suggestion
    path: '/map',
```

2023-04-11 09:45 UTC, markus2330 commented
@Benjaminimal @badnames as discussed, please review this while starting to implement your own layer. If you feel confident we should merge this, please approve.

2023-04-15 08:53 UTC, Benjaminimal approved these changes
Looks very usable.
The next step would be those side panes with tools and such.
Do we have an issue for that yet?

2023-04-15 09:45 UTC, markus2330 commented
> Looks very usable.

Thanks for the review! @badnames any further comments?

> The next step would be those side panes with tools and such.
> Do we have an issue for that yet?


We already started with the implementation: #244

2023-04-18 18:00 UTC, Benjaminimal commented
Would love to get this merged soon so I'm going to hijack this and fix the merge conflicts.

2023-04-18 18:02 UTC, markus2330 commented
Yes, please go ahead :wink:

2023-04-18 18:16 UTC, Benjaminimal commented
jenkins build please

2023-04-18 18:24 UTC, Benjaminimal commented
@markus2330 
@lukashartl 
Seems like we have some issues installing npm packages on our Jenkins server.
Can you please help?
https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-215/5/pipeline/138

2023-04-19 06:48 UTC, Benjaminimal commented
jenkins build please

2023-04-19 06:57 UTC, Benjaminimal commented
Installing npm packages works again.
I'll fix the remaining issue.

2023-04-19 13:25 UTC, merged

2023-04-19 13:25 UTC, markus2330 commented
release was done, so we can merge it now!