Free membership use case
ElektraInitiative/PermaplanT pull request #288
Opened 2023-04-16 12:34 UTC by ThorbenStaufer

Added a new use case for receiving a free membership, if the user is a valuable community member.

## Basics

- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

2023-04-17 11:05 UTC, absurd-turtle approved these changes

2023-04-17 15:44 UTC, Benjaminimal reviewed
What is a membership?

2023-04-17 16:15 UTC, markus2330 commented
This should be explained in the glossary :wink:

2023-04-18 05:42 UTC, markus2330 requested changes
Thank you.

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +- **Brief:** The user receives a free membership through using the app.
```suggestion
- **Brief:** The user receives a free membership through contributions.
```

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +  - The user can receive PermaplanT points through various activities in the app, like:
```suggestion
  - The user can receive permacoins through various activities in the app, like:
```

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +  - The user can see their exact count of PermaplanT points in their profile.
```suggestion
  - The user can see their exact count of current and previous permacoins in their profile.
```

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +  - When reaching a certain milestone with the amount of gathered PermaplanT points, the user will be given the current year of membership for free.
```suggestion
  - If the user applied for the contribution membership and when reaching a certain milestone with the amount of gathered permacoins, the user will be given the current calender year of membership without compensation via money.
```

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
Please rename to "contribution_membership", free implies you get it for free, which is not the case...

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +  - PermaplanT points will be reset to zero at the end of the membership year.
We remember all permacoins of every year in a protocol (that only gets expanded and never changed). The user starts every year from 0. Please clarify this here.

```suggestion
```

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +  - The user does not gather enough PermaplanT points and has to pay the full price for this years membership.
```suggestion
  - The user does not gather enough permacoins and has to pay the full price for this years membership.
```

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +    - getting their comments on a map marked as helpful by the maps owner.
```suggestion
    - getting their comments on a map marked as helpful by the maps owner.
    - recruit of new members.
```

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +    In this case, the user can contact the PermaplanT team via official channels so that an administrator can investigate the eligibility of the user for a free membership.
This doesn't really add something to the use case, it simply states the obvious:

```suggestion
```

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +  - The user can use the app for free if (s)he is a valuable member of the community.
please avoid "free" also here.

2023-04-18 05:42 UTC, markus2330 commented on doc/usecases/gain_free_membership.md
> +  - The amount of gathered PermaplanT point in each year should be kept in the database for administrative purposes.
Should already be clear above, so probably not needed here.

2023-05-01 12:52 UTC, markus2330 approved these changes
Great job, two last minor fixes, then it can be merged (by someone else).

2023-05-01 12:52 UTC, markus2330 commented on doc/usecases/contributing_member.md
> +  - The user can use the app without compensation via money if (s)he is a valuable member of the community.
```suggestion
  - The user has the permission to use the app and to be part of the community.
```

2023-05-01 12:52 UTC, markus2330 commented on doc/usecases/contributing_member.md
> +  - Permacoins can not be transferred from the current into the next year.
```suggestion
  - Permacoins can not be transferred from the current into another year nor be exchanged to money in any way.
```

2023-05-10 15:58 UTC, markus2330 commented
jenkins build please

2023-05-22 04:19 UTC, markus2330 commented
Now part of #366

2023-05-22 04:19 UTC, closed without merging