Feature/339 frontend refactor map state
ElektraInitiative/PermaplanT pull request #378
Opened 2023-05-24 10:16 UTC by absurd-turtle

In this PR we moved the store from undo/redo into features/map_planning/store.
Furthermore we split the store into one slice for data which is tracked by the history (e.g. objects on the map)
and one slice for all data which is not tracked by the history (e.g. visibility and opacity of layers)

## Basics

- [x] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I fixed all affected decisions
- [x] I added code comments, logging, and assertions as appropriate
- [x] I translated all strings visible to the user
- [x] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

2023-05-25 11:30 UTC, Bushuo approved these changes

2023-05-25 13:40 UTC, markus2330 requested changes
Great job, please add some documentation (and ideally also tests) how we should properly use states (and probably also what was wrong before (which lead to the situation that we need refactoring) so that this use can be avoided in future).

2023-05-26 05:39 UTC, markus2330 approved these changes
Much more clear, should we also have guidelines for sub-trees?

2023-05-26 12:41 UTC, absurd-turtle commented
> Much more clear, should we also have guidelines for sub-trees?

I added some documentation on how to add a Layer in the [/doc/architecture/frontend.README](/doc/architecture/frontend.README). I don't think we necessarily need subdirectories.

2023-05-26 14:28 UTC, badnames approved these changes

2023-05-27 03:24 UTC, merged