faster Pipeline Jenkins, by merging Check- and Build-Stage
ElektraInitiative/PermaplanT pull request #448
Opened 2023-06-12 07:32 UTC by fel115

This PR is connected with the issue #241. I created this PR to test the created Pipeline on our Jenkins instance. So for now it isn't ready to merge. 

## Basics

- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-06-12 12:11 UTC, lukashartl commented
pls rebase onto latest master 😺

2023-06-19 06:15 UTC, fel115 commented
@lukashartl I think this Pipeline runs now faster, because there are less dependencies loaded twice. Maybe you could review my changes?

2023-06-19 10:43 UTC, markus2330 requested changes
Great work. Can you maybe tell us the changes in the build time?

2023-06-19 10:43 UTC, markus2330 commented on ci/Jenkinsfile
> +            /*stage('build-frontend'){
Is this commented out on purpose?

2023-06-19 10:43 UTC, markus2330 commented on ci/Jenkinsfile
> +/*stage('Build in Docker'){
Better remove if it is not needed anymore.

2023-06-20 09:47 UTC, fel115 commented
The time improvement is due to the onetime build of the docker image and the cached build dep in the docker image. So we don't have to do some tasks twice, like downloading deps.

2023-06-22 08:23 UTC, markus2330 approved these changes
LGTM, @lukashartl please also have a look if it doesn't have unintended changes to deployment.

2023-06-22 08:25 UTC, markus2330 commented
We should merge this asap, I've put the urgent label.

2023-06-22 19:57 UTC, lukashartl approved these changes
LGTM.
And since PR deploy works, DEV deploy should also work :rocket:

2023-06-22 19:58 UTC, merged