added docker usage guide and added explanation for #437
ElektraInitiative/PermaplanT pull request #460
Opened 2023-06-14 17:02 UTC by temmey

## Basics

- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-06-15 04:07 UTC, markus2330 requested changes
Great job, thanks for your first PR! I invited you in the team.

2023-06-21 14:13 UTC, markus2330 commented
Something went wrong here, please rebase properly or create a new branch with your commits on top of it (cherry-pick). You can ask e.g. @badnames how to do this.

2023-06-21 14:52 UTC, temmey commented on doc/backend/01setup.md
> +CREATE EXTENSION IF NOT EXISTS postgis;
fixed in [4501f86](https://github.com/ElektraInitiative/PermaplanT/pull/460/commits/4501f86e91b4a64444277d71acd885ce3522d4e0)

2023-06-21 14:52 UTC, temmey commented on doc/backend/README.md
> +Instead of setting up psql server on your local machine, you could use a 'postgis' Docker container as another option.
fixed in [0716c39](https://github.com/ElektraInitiative/PermaplanT/pull/460/commits/0716c39c6729cbea51845030365daa9ae6b7775f)

2023-06-21 14:53 UTC, temmey commented on doc/backend/01setup.md
> +The user named 'permaplant' doesn't have the required permissions to start the 'postgis' extension. You'll have to set it up yourself using the postgres user.
fixed in [4501f86](https://github.com/ElektraInitiative/PermaplanT/pull/460/commits/4501f86e91b4a64444277d71acd885ce3522d4e0)

2023-06-22 13:19 UTC, markus2330 commented
There is still something wrong in the rebase, please verify that https://github.com/ElektraInitiative/PermaplanT/pull/460/files contains exactly and exclusively the changes you want. You can also reopen the branch/PR if you don't know what happened.

There are some build server issues, too. See doc/ci.md

2023-06-22 13:19 UTC, markus2330 commented
jenkins build please

2023-06-26 13:06 UTC, markus2330 commented
I assume #503 is the follow up. Please reopen if needed.

2023-06-26 13:06 UTC, closed without merging