Base layer
ElektraInitiative/PermaplanT pull request #465
Opened 2023-06-16 16:48 UTC by badnames

The old branch/pull request had far too many changes and grew to an unmanageable size.

## Basics

- [x] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-06-16 18:42 UTC, markus2330 commented
Unfortunately, I see "Die Baselayer-Datei konnte nicht geladen werden!" when being logged in on https://pr.permaplant.net and using a file that should exist. Am I doing something wrong?

2023-06-16 18:44 UTC, markus2330 commented
As said, more specific error messages would be very helpful. @absurd-turtle how is the progress for a file selector? Then some type of errors would be more obvious.

2023-06-17 08:09 UTC, badnames commented
> Unfortunately, I see "Die Baselayer-Datei konnte nicht geladen werden!" when being logged in on https://pr.permaplant.net and using a file that should exist. Am I doing something wrong?

Might be a CORS issue, but I have to look into it. How can I access the relevant branch on pr.permaplant.net?

2023-06-17 08:15 UTC, markus2330 commented
jenkins build please

2023-06-17 08:16 UTC, markus2330 commented
If nobody pushed it is still there, otherwise it will be again there after the build finishes. See also doc/ci.md

2023-06-17 13:29 UTC, badnames commented
I added some code that produces more detailed error messages.

After trying to load the image, the following error was thrown:
"Error loading base layer: TypeError: Url must be a string. Received undefined"

This error also occurs in https://pr.permaplant.net/webdav while trying to upload an image.
Ergo: this does not seem to be an issue with the base layer.

@markus2330, @lukashartl @absurd-turtle Is the Nextcloud base URL set correctly on pr.permaplant.net?

2023-06-19 05:46 UTC, markus2330 requested changes
> "Error loading base layer: TypeError: Url must be a string. Received undefined"

I can only confirm, I get the same error. And no frog on the map. :cry:

2023-06-19 05:46 UTC, markus2330 commented on frontend/src/components/Form/SimpleFormInput.tsx
> +  extends React.InputHTMLAttributes<HTMLInputElement> {
Please add documentation at least for new elements.

2023-06-19 05:46 UTC, markus2330 commented on frontend/src/config/i18n/de/baseLayer.json
> +  "loadingFailed": "Fehler beim laden des Baselayers: ",
```suggestion
  "loadingFailed": "Fehler beim Laden des Baselayers: ",
```

2023-06-19 05:46 UTC, markus2330 commented on frontend/src/config/i18n/de/baseLayer.json
> +  "notAnImage": "Der gewählte Baselayer Hintergrund ist keine Bilddatei!"
```suggestion
  "notAnImage": "Der gewählte Baselayer Hintergrund ist leider keine Bilddatei."
```

2023-06-20 17:55 UTC, merged

2023-06-20 17:57 UTC, markus2330 commented
Finally it is done, good work! :1st_place_medal: :heart: :partying_face: 

Let us see if it works on dev.permaplant.net (see also  #486)

@badnames Please create follow-up issues as necessary so that we clearly see what is missing in the base layer UC.