Finish plant search
ElektraInitiative/PermaplanT pull request #526
Opened 2023-06-29 12:06 UTC by badnames

I checked the plant search use case and it seems to be fully implemented.

## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-06-29 12:53 UTC, markus2330 requested changes
There are two left-over issues which should be mentioned in the use case:

#379 #433

2023-06-29 12:53 UTC, markus2330 commented on doc/CHANGELOG.md
> +- Finish plant search usecase.
Please link to the usecase

2023-06-30 04:52 UTC, markus2330 commented
Please also rebase and make sure to write a manual test protocol, see #519

2023-06-30 05:05 UTC, markus2330 commented
I clarified definition of done of UC in #518

2023-07-06 08:19 UTC, markus2330 requested changes
Thanks for the protocol, it looks nice. But not all links in the use case were created as requested in "DoD" (definition of done).

2023-07-06 08:19 UTC, markus2330 commented on doc/CHANGELOG.md
> +## 0.2.0 - 27.06.2023
Something went wrong in the rebase.

```suggestion
## 0.2.0 - 29.06.2023
```

2023-07-06 08:19 UTC, markus2330 commented on doc/CHANGELOG.md
> +-
```suggestion
- _()_
```

2023-07-06 08:19 UTC, markus2330 commented on doc/tests/protocols/plant_search.md
> +This is the raw template for executing a manual test.
```suggestion
```

2023-07-06 08:19 UTC, markus2330 commented on doc/tests/protocols/plant_search.md
> +Followup issues were recorded and a note has been left in the use case document.
```suggestion
Follow-up issues were recorded and a note has been left in the use case document.
```

2023-07-06 08:19 UTC, markus2330 commented on doc/usecases/done/search_plants.md
> +# Followup
```suggestion
# Follow-up

```

2023-07-06 08:19 UTC, markus2330 commented on doc/usecases/done/search_plants.md
> +Followup issues have been created in GitHub, outlining what work still needs to be done.
Please link these issues here and please also link the protocol. See doc/usecases/README.md for which links are expected.

```suggestion

```

2023-07-11 14:15 UTC, markus2330 commented
> some days before a bigger release

We are hopefully a few days before :wink: If we don't start now, we never can get done next week.

> Also what do you think about the markdown table, should we maybe switch to a bullet point format

For me bullet points are easier. (Or the `- [ ]` version if something is to check).

2023-07-11 14:20 UTC, markus2330 approved these changes
Please rebase, otherwise fine. (Table looks very nice.)

2023-07-11 14:20 UTC, markus2330 commented on doc/CHANGELOG.md
> +- Finish implementation of seed search _(Moritz)_
use random position to avoid merge conflicts (as happened now)

2023-07-11 14:20 UTC, markus2330 commented on doc/usecases/done/search_plants.md
> +Some parts of this use cases have not been implemented in preperation for a future university course.
```suggestion
```

2023-07-13 19:48 UTC, badnames commented
> Thanks for creating a manual test for this use case, you did not have to perform it yet though, usually they are performed some days before a bigger release with all the existing use cases to reveal regression (maybe I need to add that to the testing strategy, so it's clearer). However, well documented. Also what do you think about the markdown table, should we maybe switch to a bullet point format or did you use some table to markdown converter for that. Because I also wrote down some tests and for productivity it wasn't the best for me.

Thanks for the feedback.

I think bullet points would make it far easier to edit the protocol.

2023-07-13 19:48 UTC, merged

2023-07-15 12:33 UTC, markus2330 commented
@badnames please don't self-merge. This PR broke the CI (fixed in  #629)