Feature/#55 avoid unwrap expect
ElektraInitiative/PermaplanT pull request #58
Opened 2023-02-23 19:47 UTC by kitzbergerg

Deny expect and unwrap like discussed in #55. For now allow already existing expect. Depending on whether those can actually fail we might later on remove those as well.

Fix other clippy warnings as well as they would be quite annoying when adding a clippy check to ci.

2023-02-24 06:21 UTC, markus2330 requested changes
Thank you for the PR! :rocket:

> Deny expect and unwrap like discussed in https://github.com/ElektraInitiative/PermaplanT/issues/55. For now allow already existing expect. Depending on whether those can actually fail we might later on remove those as well.

Please actually check (by docu etc.) if they can fail. Every `allow(clippy` should have a comment why and for which specific purpose there is this exception.

See #60.

> Fix other clippy warnings as well as they would be quite annoying when adding a clippy check to ci.

Are there still clippy warnings? If so, please create an issue (and let us keep this PR short).

2023-02-24 06:21 UTC, markus2330 commented on backend/src/services/seed_service.rs
>      let mut conn = pool.get().expect("Failed to retrieve pool.");
Is there maybe some way to reconnect?

2023-02-25 13:57 UTC, kitzbergerg commented
> Please actually check (by docu etc.) if they can fail. Every allow(clippy should have a comment why and for which specific purpose there is this exception.

There is now only one exception where expect is used and that is when setting up the initial connection.

> Are there still clippy warnings? If so, please create an issue (and let us keep this PR short).

I fixed them as part of this PR (there we only like 3 errors and all of just something like using return ...; instead of implicit return

2023-02-26 09:27 UTC, merged

2023-02-26 09:51 UTC, markus2330 commented
Thank you, great job!