CI: Build Stage
ElektraInitiative/PermaplanT pull request #59
Opened 2023-02-23 21:58 UTC by lukashartl

Building frontend and backend

2023-02-25 06:21 UTC, markus2330 requested changes
Please add dev documentation how CI works, which should also clarify when database gets reset.

Otherwise LGTM, maybe it is possible to have the scripts also working outside CI context (if not, it is fine, too).

2023-02-25 06:21 UTC, markus2330 commented on ci/build-scripts/build-backend.sh
> +source /opt/rust.env
Why not fail here on errors?

2023-02-25 06:21 UTC, markus2330 commented on ci/build-scripts/build-backend.sh
> +export DATABASE_URL=postgres://cidb:cidb@127.0.0.1/cidb
What about setting this in ci/Jenkinsfile to keep the script more useful for devs? https://www.jenkins.io/doc/pipeline/tour/environment/

2023-02-25 06:21 UTC, markus2330 commented on ci/build-scripts/build-backend.sh
> +sudo /usr/local/bin/permaplant-reset-ci.sh
Same here: maybe this can be done outside. It should be also clear at which pipelines it is done (at least write this in a comment).

2023-02-25 06:21 UTC, markus2330 commented on ci/build-scripts/build-frontend.sh
> +set -ex
```suggestion
echo "building frontend"

# Echo on and fail fast
set -ex

cd ./frontend/
```

2023-02-26 15:26 UTC, lukashartl commented
/cc @markus2330 
Updated. Can be merged. Please `Squash and merge`.
I'll create a new PR for the Dev-Instance, so we can at least do the test builds on all PRs from now :)

2023-02-26 17:44 UTC, markus2330 approved these changes
LGTM, why do you want it squashed? Is there something within the commits which shouldn't be published? If not, I would prefer to have original commits. They are sometimes insightful how/why something was done.

2023-02-26 18:21 UTC, lukashartl commented
> LGTM, why do you want it squashed? Is there something within the commits which shouldn't be published? If not, I would prefer to have original commits. They are sometimes insightful how/why something was done.

I am ok with either ways :) 

I just thought that we don't need that many "trying things out"-commits.

2023-02-26 18:39 UTC, merged