Feature/547 timeline edit plantings dates in sidebar
ElektraInitiative/PermaplanT pull request #652
Opened 2023-07-16 16:22 UTC by Bushuo

Ref: #547  

## Basics

- [X] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [X] The PR is rebased with current master.
- [X] Details of what you changed are in commit messages.
- [X] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [x] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I fixed all affected decisions
- [ ] I added unit tests for my code
- [x] I added code comments, logging, and assertions as appropriate
- [x] I translated all strings visible to the user
- [x] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [x] I created left-over issues for things that are still to be done
- [x] Code is conforming to [our Architecture](/doc/architecture)
- [x] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [x] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-07-17 05:46 UTC, markus2330 commented
jenkins build please

2023-07-17 10:18 UTC, markus2330 requested changes
Thank you for the PR! We noticed following, please create follow-up issues if it is out-of-scope for this PR:

- [ ] when selecting German, the date format should be German
- [ ] there should be some text explaining what "delete plant" and "remove plant" means
- [ ] "remove plant" and the button "delete plant" should be visually better separated
- [ ] button "delete plant" should be smaller

2023-07-17 10:18 UTC, markus2330 commented on doc/CHANGELOG.md
> +- Add/Remove date of plants can be changed in the toolbar. Added `zod` as form validation library. _(Paul)_
Use extra lines for independent parts. Please write a line in solution when to use typeshare and when zod.

2023-07-17 10:18 UTC, markus2330 commented on frontend/src/config/i18n/en/plantings.json
> +}
Shouldn't be "delete planting" translation text in the same file?

2023-07-17 12:37 UTC, Bushuo commented
@markus2330 
> when selecting German, the date format should be German

The representation of the default browser date input is handled by the browser language. We would need a custom solution if we want to change how it looks currently.

>  there should be some text explaining what "delete plant" and "remove plant" means
 "remove plant" and the button "delete plant" should be visually better separated
 button "delete plant" should be smaller

Everything else I will do later today in this PR :)

2023-07-17 12:48 UTC, Bushuo commented
@markus2330 
If we go for a custom solution here I would suggest we use https://ui.shadcn.com/docs which is built upon https://www.radix-ui.com/
It is compatible with tailwindcss (that we use for styling), is headless (can be customized to the very last detail) and can be adopted one component at a time.
I would then also suggest that we swap out the selects and other form components for the ones in shadcn later.
The solution would follow the WAI-ARIA guidelines by default.

2023-07-17 13:53 UTC, markus2330 commented
I like the idea but it is nothing we should do soon. Let us see if anyone in the user study has English browser settings and selects `De`. :wink: I created  #656

2023-07-18 08:25 UTC, Bushuo commented
jenkins build please

2023-07-18 11:15 UTC, merged