693 fix plant names
ElektraInitiative/PermaplanT pull request #694
Opened 2023-07-24 19:43 UTC by temmey

## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [x] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [x] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [x] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [x] Code is conforming to [our Architecture](/doc/architecture)
- [x] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [x] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-07-24 22:43 UTC, temmey commented
jenkins build please

2023-07-25 04:00 UTC, markus2330 commented
jenkins build please

2023-07-25 04:22 UTC, markus2330 requested changes
Great work. Only the eye should either be functional or not be there.

2023-07-25 04:22 UTC, markus2330 commented on frontend/src/features/map_planning/components/Map.tsx
> +              <IconButton
Please comment out/revert so that we can merge this.

2023-07-25 06:35 UTC, merged

2023-07-25 06:35 UTC, markus2330 commented
Great job, good to have this!