Bugfix/756 disable retry nextcloud image loading
ElektraInitiative/PermaplanT pull request #771
Opened 2023-08-02 15:18 UTC by absurd-turtle

Disabled the retry on images in the plant list.
I also disabled the error messages on images from the plant list because currently there is no way to check which plants have an icon already.

## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-08-02 17:09 UTC, Bushuo approved these changes
Good work, but please try my suggestion.

2023-08-02 17:09 UTC, Bushuo commented on frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx
> +          retry={false}
Did you try something like this? Maybe it makes sense to retry in the other cases.
Code does not work here, but such a function can be passed to the `useQuery` hook.
```ts
          retry={(failureCount, error) => {
              if(check if error is network 404 error) return false;
              return true;
          }}
```

2023-08-02 17:09 UTC, Bushuo commented on frontend/src/features/nextcloud_integration/components/PublicNextcloudImage.tsx
> +  retry: boolean;
Maybe pass the retry type from react query here for flexibility

2023-08-02 17:09 UTC, Bushuo commented on frontend/src/features/nextcloud_integration/hooks/usePublicImage.tsx
> +  retry: boolean;
Here as well.

2023-08-03 05:00 UTC, markus2330 commented
jenkins build please

2023-08-03 05:01 UTC, markus2330 requested changes
Thank you for the PR! Frontend build unfortunately fails. Please also check out @Bushuo's improvement suggestions.

2023-08-03 07:35 UTC, absurd-turtle commented
> Thank you for the PR! Frontend build unfortunately fails. Please also check out @Bushuo's improvement suggestions.

I saw there are still some issues. Will fix it today.

2023-08-03 07:45 UTC, markus2330 commented
The user study is already 17:00, so the earlier this can be fixed, the better :rocket:

2023-08-03 09:26 UTC, merged

2023-08-03 09:28 UTC, markus2330 commented
Great work, thank you!

Are you working on debouncing or should we release as is? (If not further bugs are found.)

2023-08-03 11:10 UTC, absurd-turtle commented
> Great work, thank you!
> 
> Are you working on debouncing or should we release as is? (If not further bugs are found.)

I might look into it today but probably won't finish. So not happening in this release.