Highlighting user actions in editor tour
ElektraInitiative/PermaplanT pull request #790
Opened 2023-08-05 07:22 UTC by ThorbenStaufer

Tour steps containing an action the user should perform now have following formatting:
- A colored border around the step.
- The text detailing the action is displayed semi-bold.
- The text detailing the action is displayed in color.
- The text detailing the action is displayed as a new paragraph.

## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-08-05 08:43 UTC, ThorbenStaufer commented
jenkins build please

2023-08-05 13:11 UTC, markus2330 commented
jenkins build please

2023-08-05 13:46 UTC, markus2330 requested changes
Great work! A few improvements are needed.

2023-08-05 13:46 UTC, markus2330 commented on frontend/src/config/i18n/de/guidedTour.json
>          "plants_layer_select": "Nutze das Ebenen-Panel und klicke jetzt auf die angezeigte Schaltfläche, um zur Pflanzen-Ebene zu wechseln und Zugriff auf deren Funktionen zu bekommen.",
```suggestion
        "plants_layer_select_text": "Nutze das Ebenen-Panel, um zur Pflanzen-Ebene zu wechseln und Zugriff auf deren Funktionen zu bekommen.",
        "plants_layer_select_action": "Klicke jetzt auf die angezeigte Schaltfläche rechts vom Pfeil.",
```

2023-08-05 13:46 UTC, markus2330 commented on frontend/src/config/i18n/en/guidedTour.json
>          "plants_layer_select": "Use the layers panel and click now on the highlighted button to switch to the plants layer and get access to its features.",
```suggestion
        "plants_layer_select_text": "Use the layers panel to switch to the plants layer and get access to its features.",
        "plants_layer_select_action": "Click now on the button indicated by the arrow.",
```

2023-08-05 13:46 UTC, markus2330 commented on frontend/src/config/i18n/de/guidedTour.json
> +        "plants_layer_first_planting_select_action": "Suche jetzt nach einer Tomate und klicke sie an, um in den Platzierungsmodus zu wechseln.",
Put this text field higher (where the search text should be written). Please check if quotes work.

```suggestion
        "plants_layer_first_planting_select_action": "Tippe jetzt den Suchbegriff \"Tomate\" ein. Wähle dann per Mausklick die Tomate aus, um in den Platzierungsmodus zu wechseln.",

```

2023-08-05 13:46 UTC, markus2330 commented on frontend/src/config/i18n/en/guidedTour.json
> +        "plants_layer_first_planting_select_action": "Search now for a tomato and click it to switch to placing mode.",
```suggestion
        "plants_layer_first_planting_select_action": "Now type the search term \"tomato\". Then click on the tomato to switch to placing mode.",
```

2023-08-05 13:46 UTC, markus2330 commented on frontend/src/config/i18n/de/guidedTour.json
> +        "plants_layer_second_planting_select_text": "Nun suchst du nach einer Kartoffel.",
Put this text field higher (where the search text should be written).

2023-08-07 09:13 UTC, markus2330 approved these changes
Well done, we are very happy with the tour! :heart:

2023-08-07 09:14 UTC, merged