Move UC to done
ElektraInitiative/PermaplanT pull request #833
Opened 2023-08-16 14:31 UTC by ThorbenStaufer

## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-08-17 05:18 UTC, markus2330 requested changes
- [ ] Please write about current status (with links where code is etc.) of gain_blossoms but leave it in assigned
- [ ] write a new use case (directly in done) that describes the tour, also with links to code etc.

2023-08-18 08:31 UTC, markus2330 requested changes
Great job, beautiful summary of where is what. Please also add changelog. Please also add left-over issues (translation of guided tour).

2023-08-18 08:31 UTC, markus2330 commented on doc/usecases/done/guided_tour.md
> +- CSS classes for the styling of the tour were added as a seperate [CSS file](https://github.com/ElektraInitiative/PermaplanT/blob/e4931dc6b4e1bbfaa48a6094a7c289f3cd2de57c/frontend/src/styles/guidedT
"doc/usecases/done/guided_tour.md:35: seperate ==> separate" see CI

```suggestion
- CSS classes for the styling of the tour were added as a separate [CSS file](https://github.com/ElektraInitiative/PermaplanT/blob/e4931dc6b4e1bbfaa48a6094a7c289f3cd2de57c/frontend/src/styles/guidedTour.css).
```

2023-08-18 08:31 UTC, markus2330 commented on doc/usecases/done/guided_tour.md
> +  - The user is registered and logged in.
```suggestion
  - The user is member and logged in.
```

2023-08-18 08:31 UTC, markus2330 commented on doc/usecases/done/guided_tour.md
> +- **Actors:** App User
Keep consistent to as used below.

```suggestion
- **Actors:** User
```

2023-08-18 08:31 UTC, markus2330 commented on doc/usecases/done/guided_tour.md
> +  - The user has previously not completed the guided tour.
```suggestion
  - The user has not previously completed the guided tour.
```

2023-08-18 08:31 UTC, markus2330 commented on doc/usecases/done/guided_tour.md
> +  The user is shown a guided tour, that explains the features of the map editor based on a small scenario.
```suggestion
  The user is shown a guided tour, which explains the features of the map editor based on a small scenario.
```

2023-08-18 08:31 UTC, markus2330 commented on doc/usecases/done/guided_tour.md
> +  After completing the guided tour, the user is awarded a [Blossom](assigned/gain_blossoms.md).
```suggestion
  After completing the guided tour, the user is awarded a [Blossom](../assigned/gain_blossoms.md).
```

2023-08-18 08:31 UTC, markus2330 commented on doc/usecases/done/guided_tour.md
> +  Upon cancel, the user can decide to complete it later and see it on their next visit to the map editor or cancel it indefinitely.
```suggestion
  Upon cancel, the user decides to see it on their next visit or to cancel it indefinitely.
```

2023-08-18 08:38 UTC, ThorbenStaufer commented
> translation of guided tour

Tour translation already has an open issue with #710.

2023-08-18 09:01 UTC, markus2330 approved these changes
> Tour translation already has an open issue with https://github.com/ElektraInitiative/PermaplanT/issues/710.

Yes, this should be linked in the UC (see also other done UC), as it is not possible in GitHub to filter for issues related to a UC.

2023-08-18 11:54 UTC, markus2330 commented
jenkins build please

2023-08-18 12:36 UTC, merged