Seed delete confirmation and undo.
ElektraInitiative/PermaplanT pull request #881
Opened 2023-08-29 12:35 UTC by badnames

## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-08-30 07:06 UTC, markus2330 commented
jenkins build please

2023-08-30 08:18 UTC, markus2330 requested changes
Great job, I love the undo button in the toast, looks&feel great. This also seems to fix the "Hello" greeting after removing a seed. The confirmation before, however, seems to be unnecessary and its text wrong (as you can press undo). Please remove this confirmation.

2023-08-30 13:05 UTC, badnames commented
The modal is now removed.

2023-08-30 13:19 UTC, badnames commented
@markus2330 there is a small caveat to restoring seeds I should mention:

Deleted seeds are immediately removed from the backend.
If a user chooses to redo the deletion the seed is resubmitted to our database as if it were a new seed (it gets a new id).

This does not seem to cause problems in the editor at the moment, because it ignores the seeds data completely.
However, if this changes in the future deleting and then restoring old seeds might also remove plants from maps without the user noticing.

2023-09-01 17:39 UTC, badnames commented
> This really is problematic. 

Yes I only noticed that seeds might have to keep their ids after implementing this feature.

> Isn't there a way to send the delete request only if undo wasn't pressed?

In theory absolutely.
However in practice this seems to be again much harder than initially expected.
The main issue is that the timing of the API-calls is very inaccurate.
Sometimes seeds were not actually deleted until several minutes after pressing the delete button.
 
Here is a short summary of the things I have tried locally:

### Delete the seed once react-toastify's toast.onChange callback indicates that the undo toast was closed.

Actual deletes would only happen more than 30 seconds after the toast has vanished.
While debugging I also noticed that the callback was perpetually executed in an infinite loop after this point.

This might have been an error on my side, but if it was I could absolutely not figure out what was wrong.
The documentation of this feature is unfortunately very sparse (https://fkhadra.github.io/react-toastify/listen-for-changes/). 

### Same as above but using react-toastify's legacy onClose callback.

This method did basically the opposite of what I was expecting. 
Seeds would be deleted the instant the toast appeared on the screen.
Once the toast was removed, no callback fired whatsoever (?).

According to various online sources I am apparently not the only one experiencing this.

### custom solution using setTimeout

I started a timer that executed in parallel to the toast.
Like in the first example, the callback for deleting the seed was called sometimes several seconds to minutes after it should have been called. 
This is probably just a sign that there is a lot of code running in the background that prevents the timers from executing (https://stackoverflow.com/questions/34691428/javascript-event-queue-and-settimeout).

2023-09-01 17:46 UTC, badnames commented
Possible solutions:

- Keep the current solution and document the mentioned caveat so that we can deal with it once it causes problems (probably not the best idea).
- Modify the backend in such a way that seeds can be resubmitted with old IDs
- Implement a more elaborate undo mechanism where seeds are only marked as deleted in the backend (such that they are not returned in fetch requests) with a cronjob that removes all marked seeds after a specified period of time.

2023-09-02 08:41 UTC, markus2330 commented
@badnames Thx for the detailed investigations, good job! :heart: 

I talked with @yvonnemarkl and we will do the following:

- there shouldn't be a "delete" but call it "archive" instead
- the icon should be archive-off from https://tablericons.com/
- "archive" is a boolean in the seeds database
- the "archive" button and the "undo" toggle that flag in the seeds database
- as it is not a deletion, we don't need a cronjob and there cannot be plant referencing to deleted seeds

Currently, archived seeds should not be shown by default but a user can switch to show only archived seeds (similar to Nextcloud Deck). But better keep this in an left-over issue, as this feature is not urgent/release critical. As always: Please create the left-over issues as needed.

2023-09-06 18:17 UTC, badnames commented
@markus2330 I have used the icon "archive" (also from tabler icons).
This was done because the meaning of "archive-off" would usually be the opposite in other applications and websites.

If you still prefer the other icon, this can be trivially changed.

2023-09-07 05:11 UTC, markus2330 commented
jenkins build please

2023-09-07 05:22 UTC, markus2330 commented
jenkins build please

2023-09-07 05:34 UTC, markus2330 commented
The CI didn't run through?

> @markus2330 I have used the icon "archive" (also from tabler icons).
> This was done because the meaning of "archive-off" would usually be the opposite in other applications and websites.

In our case you press this button (to archive the seed) if you **take out** the (physical) seeds from your (physical) box (or you don't have it in your physical box anymore for whatever reason), so the reverse symbol makes more sense.

The overview of (non-archived) seed should correspond 1:1 with the content of the box.

Here an update on the use case, please include in the PR:

```diff
diff --git a/doc/usecases/current/entry_list_seeds.md b/doc/usecases/current/entry_list_seeds.md
index 0c61f1b7..cf5ad945 100644
--- a/doc/usecases/current/entry_list_seeds.md
+++ b/doc/usecases/current/entry_list_seeds.md
@@ -5,7 +5,7 @@
 - **Scope:** Seed Management
 - **Level:** User Goal
 - **Actors:** App User
-- **Brief:** The users manage their seeds by adding, editing, and deleting them in the app.
+- **Brief:** The users manage their seeds by adding, editing, and archiving them.
 - **Assignee:** Moritz
 
 ## Scenarios
@@ -14,13 +14,13 @@
   The user has opened the seed management feature in the app.
 - **Main success scenario:**
   - The user is able to add new seeds to their list.
-  - The user is able to view a list of seeds where plant name, additional name, harvest year, amount, and origin is visible.
-  - The user is able to edit or delete seeds of the list.
+  - The user is able to view a list of seeds where the complete name, amount, quality, harvest year, and origin is visible.
+  - The user is able to edit or archive seeds of the list.
 - **Alternative scenario:**
-  The user accidentally deletes a seed from their list and uses the undo feature to correct it.
+  The user accidentally archives a seed from their list and uses the undo feature to correct it.
 - **Error scenario:**
-  There is an error when the user attempts to add a seed to their list, such as an invalid expiration date or a seed with the same name already existing.
-  In this case, the app validates while the user is typing and shows a validation error.
+  There is an error when the user attempts to add or edit a seed entry with invalid data such as an invalid price.
+  In this case, the app validates when saving the seed and shows a validation error.
 - **Postcondition:**
-  The user's seed list is updated with the added, deleted, or restored seeds.
+  The user's seed list corresponds exactly with the physical seeds in the user's seed box in reality.
```

2023-09-07 13:37 UTC, markus2330 commented
@badnames please also add hover text for the two actions, "archive seed" and "edit seed" (to complete the archive functionality, added it to #872)

2023-09-10 14:09 UTC, markus2330 requested changes
functionality looks much better now, I didn't test it though. Please add test protocol.

2023-09-10 14:09 UTC, markus2330 commented on backend/src/model/enum/include_archived_seeds.rs
> +    #[serde(rename = "not_archvied")]
```suggestion
    #[serde(rename = "not_archived")]
```

2023-09-10 14:09 UTC, markus2330 commented on doc/changelog.md
> +- Enable undo for seed deletion _(Moritz)_
Does not fully match to the PR anymore.

2023-09-10 14:09 UTC, markus2330 commented on doc/usecases/current/entry_list_seeds.md
> -# Use Case: Entry and List of Seeds
Something went wrong here.

2023-09-11 07:59 UTC, markus2330 approved these changes
Worked great in a quick test! :heart:

2023-09-11 08:03 UTC, markus2330 reviewed
Some follow ups...

2023-09-11 08:03 UTC, markus2330 commented on frontend/src/icons/archive.svg
File not needed?

2023-09-11 08:03 UTC, markus2330 commented on frontend/src/icons/archive-off.svg
Should be in public, see #355. .reuse/dep5

2023-09-11 16:12 UTC, 4ydan commented
What is the linked issue here again?

2023-09-11 16:17 UTC, 4ydan commented
I am very confused, where are the archived seeds going, how can I see the archive?

2023-09-11 16:21 UTC, badnames commented
> I am very confused, where are the archived seeds going, how can I see the archive?

Archived seeds stay in the database but are marked using an additional archive date property.
At this point in time archived seeds are not displayed to the user.
In the future they will be displayed seperatelay, allowing the user to unarchive them if desired.

2023-09-11 16:21 UTC, 4ydan commented
When deleting two seeds back to back you can not restore both, maybe this is a very rare edge case, but still.

2023-09-12 17:57 UTC, markus2330 commented
>  It would have been better to just show a warning before deletion, as there is no archive for the user at this point.

If there is an undo, we don't need a confirmation. (#900)

>  if we put the notes field next to generation

No, notes field should get bigger, so it does not fit.

> Edit: It was because of older inserted seeds not having the archive attribute.

The PR should also work for older seeds inserted from previous versions. For old seeds, we can simply assume they are not archived. What exactly is wrong here or how is the behavior?

2023-09-13 10:16 UTC, 4ydan commented
Can this be merged? @badnames

2023-09-13 10:18 UTC, 4ydan commented
> The PR should also work for older seeds inserted from previous versions. For old seeds, we can simply assume they are not archived. What exactly is wrong here or how is the behavior?

Its just that you cant restore seeds without the archive attribute

2023-09-13 13:12 UTC, markus2330 commented
jenkins build please

2023-09-13 13:42 UTC, markus2330 requested changes
A few things still to be fixed. I also encountered a weird problem where two toasts said that the same seed was restored. I cannot reproduce it, however. But maybe you find a way how to make the code more robust.

2023-09-13 13:42 UTC, markus2330 commented on backend/src/model/dto.rs
> +#[allow(clippy::missing_docs_in_private_items)] // TODO: See #97.
Please remove

```suggestion
```

2023-09-13 13:42 UTC, markus2330 commented on backend/src/controller/seed.rs
> +///
Mention that the timestamp will be recorded. (which btw. is a very nice solution)

2023-09-13 13:42 UTC, markus2330 commented on frontend/public/icons/archive-off.svg
1. Still not in .reuse/dep5`
2. It looks like you need to undo the revert: I get the warning ```Assets in public cannot be imported from JavaScript. Instead of /public/icons/archive-off.svg, put the file in the src directory, and use /src/icons/archive-off.svg instead. (x3)` #355

2023-09-13 13:53 UTC, markus2330 commented
> Its just that you cant restore seeds without the archive attribute

Cannot reproduce. For me archive&restoring also works for seeds that were created before this PR.

2023-09-14 10:18 UTC, badnames commented
> > Its just that you cant restore seeds without the archive attribute
> 
> Cannot reproduce. For me archive&restoring also works for seeds that were created before this PR.

At least in theory every existing seed should get the new archived_at column that is initially set to null.

2023-09-14 12:10 UTC, markus2330 commented
@4ydan we also need test cases with more than 30 objects, as this is our page size.

2023-09-14 14:33 UTC, badnames commented on frontend/src/icons/archive-off.svg
I could not find any licensing info on tablericons.com.
It only says "No attribution required" and "For comercial use".

2023-09-14 14:40 UTC, badnames commented
> @4ydan we also need test cases with more than 30 objects, as this is our page size.

@markus2330 Thank you for providing console output this time. 
This makes troubleshooting much quicker and easier.
  
Also: the error had nothing to do with the amount of seeds on the page. 
There was simply a missing enum value in the hook useTranslateQuantity (it says so right in the error message).

2023-09-14 15:41 UTC, markus2330 commented on frontend/src/icons/archive-off.svg
Yes, you can copy this text as-is, together with the URL from where we got it from.

2023-09-14 15:46 UTC, merged