Fix seed form validation bugs
ElektraInitiative/PermaplanT pull request #892
Opened 2023-09-08 11:13 UTC by badnames

## Basics

- [x] I added a line to [changelog.md](/doc/changelog.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

2023-09-08 11:44 UTC, 4ydan approved these changes
Looks good to me. Issue looks fixed.

2023-09-08 13:19 UTC, markus2330 commented
44.4 and abc didn't work for me on pr.permaplant.net? I'll rebuild and check again.

2023-09-08 13:19 UTC, markus2330 commented
jenkins build please

2023-09-08 13:38 UTC, markus2330 requested changes
Thank you for the fix! Please improve the error message. Can you also allow "," as comma? (okay if it is accepted for both German and English)

2023-09-08 13:38 UTC, markus2330 commented on frontend/src/config/i18n/de/seeds.json
>      "error_price_must_be_number": "Der Preis muss eine Zahl sein. z.B. 2,99",
I only get "please enter a number" and not this text? And the error can be improved:

```suggestion
    "error_price_must_be_number": "Entschuldigung, der Preis muss eine Zahl mit . als Komma sein. z.B. 2.99",

```

2023-09-08 13:38 UTC, markus2330 commented on frontend/src/config/i18n/de/seeds.json
>      "placeholder_price": "2,99€",
```suggestion
    "placeholder_price": "2.99€",

```

2023-09-08 13:38 UTC, markus2330 commented on frontend/src/config/i18n/en/seeds.json
>      "placeholder_price": "2,99€",
```suggestion
    "placeholder_price": "2.99€",

```

2023-09-08 13:38 UTC, markus2330 commented on frontend/src/config/i18n/en/seeds.json
>      "error_price_must_be_number": "Price must be a number",
```suggestion
    "error_price_must_be_number": "Sorry, price must be a number with . as comma, e.g. 2.99",
```

2023-09-08 13:40 UTC, markus2330 commented on frontend/src/config/i18n/de/seeds.json
>      "error_price_must_be_number": "Der Preis muss eine Zahl sein. z.B. 2,99",
Or if we support ",", too:

```suggestion
    "error_price_must_be_number": "Entschuldigung, ich verstehe nur einen Preis als Zahl mit Punkt (.) oder Beistrich (,) als Komma, z.B. 2,99",
```

2023-09-08 16:26 UTC, badnames commented
> Can you also allow "," as comma? (okay if it is accepted for both German and English)

https://stackoverflow.com/questions/26890209/html-tag-input-of-type-number-and-culture-based-decimal-separator

The comma seperator in HTML5 input fields is tied to the browsers language. 
We could change this using the 'lang' field of the root html tag, but I don't (yet) know if and how this can be set up using react and our internationalization library.

2023-09-08 17:17 UTC, markus2330 commented
jenkins build please

2023-09-08 17:39 UTC, markus2330 commented
I still only get "please enter a number" and not the correct error text?

The error messages are now inconsistent, please fix them according what we decide in #895. In the current behavior you would need to say in both languages that it could be , or .

2023-09-08 18:40 UTC, badnames commented
> I still only get "please enter a number" and not the correct error text?

> The error messages are now inconsistent, please fix them according what we decide in https://github.com/ElektraInitiative/PermaplanT/issues/895. In the current behavior you would need to say in both languages that it could be , or .

I have solved the original validation problem using the default html5 constraints for number fields (min, max, step, type, etc.) in the hopes that this would simplify the form a bit.
This means that the input validation for the price field is now primarily handled by the browser, which makes its behavior apparently a bit inconsistent.

On chrome it is for example not possible to input any characters besides numbers, while Firefox allows that kind of input and only displays an error message ("please enter a number") once the user tries to submit the form.

Furthermore, Chrome seems to select the comma separator according to the users System language (German in my case) while Firefox uses '.'.
Changing the language on the site (react i18n does apparently update the 'lang' attribute of the root element) has no consistent effect on the selected comma separator.


If you wish, I could make the input behavior consistent again by implementing custom validation logic.

2023-09-09 04:17 UTC, markus2330 requested changes
Suggestions fix the inconsistent error messages.

2023-09-09 04:17 UTC, markus2330 commented on frontend/src/config/i18n/en/seeds.json
> +    "error_price_must_be_number": "Sorry, I only understand the price as a number with . as comma, e.g. 2.99",
```suggestion
    "error_price_must_be_number": "Sorry, I only understand the price as a number with dot (.) or comma (,) depending on your Browser's preferences as decimal separator, e.g. 2.99",
```

2023-09-09 04:17 UTC, markus2330 commented on frontend/src/config/i18n/de/seeds.json
> +    "error_price_must_be_number": "Entschuldigung, ich verstehe nur Zahlen mit Punkt (.) oder Beistrich (,) als Komma, z.B. 2,99",
```suggestion
    "error_price_must_be_number": "Entschuldigung, ich verstehe nur Zahlen mit Punkt (.) oder Beistrich (,) abhängig von den Browsereinstellungen als Komma, z.B. 2,99",

```

2023-09-09 04:31 UTC, markus2330 commented
> I have solved the original validation problem using the default html5 constraints for number fields (min, max, step, type, etc.) in the hopes that this would keep the form nice and simple.
> This means that the input validation for the price field is now primarily handled by the browser, which makes its behavior apparently a bit inconsistent.

Please read my text carefully, I was talking about inconsistent "error messages". I now suggested how we can fix them so that I can finally merge this PR.

> On chrome it is for example not possible to input any characters besides numbers, while Firefox allows that kind of input and only displays an error message ("please enter a number") once the user tries to submit the form.

So you say this error message is hard-coded in Firefox and cannot be changed by us?

> If you wish, I could make the input behavior consistent again by implementing custom validation logic.

I don't want to work against the Browsers but rather with them. If we fix it, we fix in in a general way like https://github.com/ElektraInitiative/PermaplanT/issues/895.

2023-09-09 14:45 UTC, badnames commented
> Please read my text carefully, I was talking about inconsistent "error messages". I now suggested how we can fix them so that I can finally merge this PR.

I know, this is just some background information on why these inconsistent error messages are displayed.

> So you say this error message is hard-coded in Firefox and cannot be changed by us?

I have not yet found any information suggesting otherwise.

2023-09-10 13:58 UTC, markus2330 approved these changes
Let us merge this, follow up #895 already exists.

2023-09-10 13:58 UTC, merged