doc: refinement of timeline use cases
ElektraInitiative/PermaplanT pull request #947
Opened 2023-10-07 12:12 UTC by danielsteinkogler

## Basics

- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

2023-10-09 05:54 UTC, markus2330 requested changes
Great work.
- [x] Please also move the UC to current.
- [x] 0 events should lead to no visual indication, so that 0 and 1 can be easily distinguished.

2023-10-09 05:54 UTC, markus2330 commented on doc/usecases/assigned/map_timeline_event_view.md
> +  - the events a represented by either a line or a bar chart on the sliders.
```suggestion
  - the events are represented by a visual indication directly at the day/month/year on the sliders.
```

2023-10-09 05:54 UTC, markus2330 commented on doc/usecases/assigned/map_timeline_event_view.md
> +  - the timeline can be scaled vertically for better graph readability.
Rationale usually not needed.

```suggestion
  - the timeline can be scaled vertically for touch screen usage.
```

2023-10-09 05:54 UTC, markus2330 commented on doc/usecases/assigned/map_timeline_single_selection.md
> +  - A timeline is presented to the user witch allows them to select year, month and day.
```suggestion
  - A timeline is presented to the user which allows them to select year, month and day.
```

2023-10-09 05:54 UTC, markus2330 commented on doc/usecases/assigned/map_timeline_single_selection.md
> +  - Year, month and day can be individually selected by scrolling or moving sliders.
```suggestion
  - Year, month and day can be individually selected by scrolling, moving sliders or clicking on the elements.
```

2023-10-09 05:54 UTC, markus2330 commented on doc/usecases/assigned/map_timeline_single_selection.md
> +  - The sliders are synchronized (e.g. if the user scrolls the day slider over the last day of the month, the month slider is updated to the next month)
see also unterlagen/english.md in submissions

```suggestion
  - The sliders are synchronized, i.e., if the user scrolls the day slider over the last day of the month, the month slider is updated to the next month
```

2023-10-09 05:54 UTC, markus2330 commented on doc/usecases/assigned/map_timeline_single_selection.md
> +  - The selected date is highlighted in bold.
```suggestion
  - The selected date is highlighted.
```

2023-10-12 13:37 UTC, danielsteinkogler commented
@markus2330 i resolved your comments and rebased on current master. i think the PR should be ready to get merged after pipeline succeeds

2023-10-12 13:38 UTC, danielsteinkogler commented
and i created some github issues based on the usecases

2023-10-13 17:08 UTC, merged

2023-10-13 17:08 UTC, markus2330 commented
Great work! :heart: